#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("myNotePad.Resource", IsApplication=true)]

namespace myNotePad
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrowright = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BackgroundStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int gradient_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gradient_bg_hover = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int list_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splashimg = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int btnAddNote = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int btnDeleteNote = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int btnEditNote = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int lbldate = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int lbltitle = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int lvNoteList = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int sqlite_id = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int txtEditNoteDescription = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int txtEditNoteTitle = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int txtNoteDescription = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int txtNoteTitle = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int txtSearch = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddNote = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditNote = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
